XY_dir: v3-binary
actv_func: sigmoid
augment_seed: 42
augmentations:
  horizontal_flip: true
  rotate_range: 45
  shear_range: 15
  vertical_flip: true
batch_size: 16
binary_loss: BCE
config_version: config_t1.vgg16.block4_pool.None.run1-with-lowAttn
epochs: 1000
heldout: null
hyperbolic_strength: null
kernel_constraint: null
kernel_regularizer: null
layer: block4_pool
lr: 0.003
model_name: vgg16
patience: 20
preprocessed_dir: v3
run: 1
size_per_class: 1023
split_ratio: 0.2
stimulus_set: 1
task: binary
train: finetune

# --- low attn ---
attn_positions: block4_pool
low_attn_constraint: nonneg
attn_initializer: ones
attn_regularizer: l1
reg_strength: 0.001
noise_distribution: 
noise_level: 
