XY_dir: v3-binary
actv_func: sigmoid
augment_seed: 42
augmentations:
  horizontal_flip: true
  rotate_range: 45
  shear_range: 15
  vertical_flip: true
batch_size: 16
binary_loss: BCE
config_version: config_t0.vgg16.flatten.None.run1
epochs: 1000
heldout: null
hyperbolic_strength: null
kernel_constraint: null
kernel_regularizer: null
layer: flatten
lr: 0.003
model_name: vgg16
patience: 20
preprocessed_dir: v3
run: 1
size_per_class: 1023
split_ratio: 0.2
stimulus_set: 0
task: binary
train: finetune
